//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P5_1Dipl_MVC_UASD_Estudiante_ImageUpload
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEstudiante
    {
        public int EstudianteID { get; set; }

        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public string Apellidos { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        [StringLength(10,MinimumLength = 10,ErrorMessage = "La propiedad {0} debe tener {1} caracteres de máximo y {2} de mínimo")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "La propiedad {0} debe tener {1} caracteres de máximo y {2} de mínimo")]
        public string Cedula { get; set; }
        public string ImagenUrl { get; set; }
    }
}
